### ISSUE TITLE
Oskorbleniya

### ISSUE THREAD

**Issue by Potriashka** [BekhruzSNiyazov/Virtual-Assistant#1]
It doesn't react on these words at all!
Like "F*ck you", "F*ck me", "Sh*t" etc. Please make it more understandable to people's language
![Screenshot from 2021-01-07 15-45-05](https://user-images.githubusercontent.com/54754814/103899628-58b3e800-50ff-11eb-837d-aa44b2e8e5dc.png)

**Comment by BekhruzSNiyazov** [comment]
I am not going to fix this.
